package com.rmompati.lang.backend;

import com.rmompati.lang.intermediate.ICode;
import com.rmompati.lang.intermediate.SymTable;
import com.rmompati.lang.message.MessageHandler;
import com.rmompati.lang.message.MessageProducer;

/**
 * <h1>Backend</h1>
 *
 * <p>The framework class that represents the back end component.</p>
 */
public abstract class Backend implements MessageProducer {

  protected static MessageHandler messageHandler;

  static {
    messageHandler = new MessageHandler();
  }

  /** The Symbol table. */
  protected SymTable symTable;

  /** The intermediate code. */
  protected ICode iCode;

  /**
   * Process the intermediate code and the symbol table generated by the parser. To be implemented by the compiler or
   * the interpreter subclass.
   * @param iCode the intermediate code.
   * @param symTable the symbol table.
   * @throws Exception if an exception occurs.
   */
  public abstract void process(ICode iCode, SymTable symTable) throws Exception;
}
